### PR TITLE
Fix the background color of the profile page

### LINKED ISSUE #346: Fix profile background color for dark mode
Currently, there is no separation between the avatar and profile background color for dark mode. Make the bg color lighter so that the avatar pops more.

image

### PR DESCRIPTION
**Pull request by jazellemaira**
This PR changes the color of the profile background on dark mode.

This PR also adjusts the margin for empty state reviews on the profile page so that it doesn't look squished.

image

image

Fixes #346

### CODE REVIEW

**Comment by nsunami** [comment]
Great work asawa! 
We may want to change this on the public profile page as well:
image

**Comment by jazellemaira** [comment]
image

**Comment by nsunami** [comment]
Fixing the merge conflict!

**Review by nsunami — APPROVED** [review]
LGTM ILY! ❤️

**Pull request merged**
